on:
  push:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/draft-pdf.yaml
  workflow_dispatch:

name: Draft JOSS PDF

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@85a18372e48f551d8af9ddb7a747de685fbbb01c # master 2024-07-17
        with:
          journal: joss
          paper-path: paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
